sudo: required

before_install:
  - gem install cocoapods -v '0.39.0'

osx_image: xcode7.2
language: objective-c

xcode_workspace: TheaterActors.xcworkspace
xcode_scheme: Actors
xcode_sdk: iphonesimulator9.2
xcode_destination: 'name=iPhone 6s,OS=9.2’